package com.example.converter.features.utils

enum class Currencies {
    USD, EUR, RUB, JPY, GBP, AUD, CAD, CHF, CNY, HKD,
    NZD, AED, AFN, ALL, AMD, ANG, AOA, ARS, AWG, AZN,
    BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, BOB, BRL,
    BSD, BTN, BWP, BYN, BYR, BZD, CDF, CLF, CLP, COP,
    CRC, CUC, CUP, CVE, CZK, DJF, DKK, DOP, DZD, EGP,
    ERN, ETB, FJD, FKP, GEL, GGP, GHS, GIP, GMD, GNF,
    GTQ, GYD, HNL, HRK, HTG, HUF, IDR, ILS, IMP, INR,
    IQD, IRR, ISK, JEP, JMD, JOD, KES, KGS, KHR, KMF,
    KPW, KRW, KWD, KYD, KZT, LAK, LBP, LKR, LRD, LSL,
    LTL, LVL, LYD, MAD, MDL, MGA, MKD, MMK, MNT, MOP,
    MRO, MUR, MVR, MWK, MXN, MYR, MZN, NAD, NGN, NIO,
    NOK, NPR, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PYG,
    QAR, RON, RSD, RWF, SAR, SBD, SCR, SDG, SEK, SGD,
    SHP, SLL, SOS, SRD, STD, SVC, SYP, SZL, THB, TJS,
    TMT, TND, TOP, TRY, TTD, TWD, TZS, UAH, UGX, UYU,
    UZS, VEF, VND, VUV, WST, XAF, XAG, XAU, XCD, XDR,
    XOF, XPF, YER, ZAR, ZMK, ZMW, ZWL, XPT, XPD, BTC,
    ETH, BNB, XRP, SOL, DOT, AVAX, MATIC, LTC, ADA
}